apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxproxymanager-data-longhorn-claim
  namespace: homelab
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxproxymanager-letsencrypt-longhorn-claim
  namespace: homelab
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi