apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: argocd
spec:
  project: appbundle-project-dev
  source:
    chart: postgresql-ha
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.0.0
    helm:
      releaseName: postgresql-ha
      # valueFiles:
      #   - postgresql-values.yml
      valuesObject:
        # This is not exposed go away hackers
        pgpool:
          adminPassword: password123
        postgresql:
          password: password123
          replicaCount: 3
          repmgrPassword: password123
        volumePermissions:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev