apiVersion: v1
kind: Secret
metadata:
  name: wireguard-secret
  namespace: wireguard
type: Opaque
stringData:
  wg0.conf.template: |
    [Interface]
    Address = {{ .Address }}
    PrivateKey = {{ .PrivateKey }}
    ListenPort = {{ .ListenPort }}
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    SaveConfig = true
    [Peer]
    PublicKey = {{ .PeerPublicKey }}
    AllowedIPs = {{ .PeerAllowedIPs }}
    Endpoint = {{ .PeerEndpoint }}
    PersistentKeepalive = {{ .PersistentKeepalive }}

    [Peer]
    PublicKey = {{ .PeerPublicKey2 }}
    AllowedIPs = {{ .PeerAllowedIPs2 }}