- hosts: all
  become: yes
  vars:
    # Must container master in the name
    control_plane: "kmaster"
    # Worker names, kworker-1 , kworker-2, kworker-3, ... kworker-{{ number_of_workers }}
    worker_prefix: "kworker"
    number_of_workers: 3
  tasks:
    - name: Create /etc/modules-load.d/k8s.conf for all worker nodes
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf

    - name: Load the modules
      shell:
        cmd: sudo modprobe overlay && sudo modprobe br_netfilter

    - name: Configure kernel parameters for all nodes
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf

    - name: Apply the changes
      shell:
        cmd: sudo sysctl --system

    - name: Create LXD container controller
      shell: |
        lxc launch ubuntu:22.04 {{ control_plane }} -c security.privileged=true -c security.nesting=true -c linux.kernel_modules=ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
        lxc file push /boot/config-5.15.0-94-generic  {{ control_plane }}/boot/
        lxc restart {{ control_plane }}

    - name: Create LXD container workers
      shell: |
        lxc launch ubuntu:22.04 {{ item }} -c security.privileged=true -c security.nesting=true -c linux.kernel_modules=ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
        lxc file push /boot/config-5.15.0-94-generic  {{ item }}/boot/
        lxc restart {{ item }}
      loop: "{{ range(1, number_of_workers|int + 1) | map('string') | map('regex_replace', '^', worker_prefix) | map('join', '') | list }}"
