- hosts: masters
  become: yes # Run as root
  # Make sure to change this
  become_user: alex
  vars:
    metallb_helm_chart_url: https://metallb.github.io/metallb
    longhorn_helm_chart_url: https://charts.longhorn.io
    nginx_helm_chart_url: https://kubernetes.github.io/ingress-nginx
    metallbstart: "10.35.40.80"
    metallbend: "10.35.40.99"
  tasks:    
    - name: Add Metallb Repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: "{{ metallb_helm_chart_url }}"
    - name: Prep Metallb
      shell: 'kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system'
    - name: Install Metallb
      kubernetes.core.helm:
        name: my-metallb
        namespace: metallb-system
        chart_ref: metallb/metallb
        create_namespace: true
    - name: Pause for deployment 
      pause:
        minutes: 1
    - name: Configure metallb IP address pool
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: first-pool
          namespace: metallb-system
        spec:
          addresses:
          - {{ metallbstart }}-{{ metallbend }}
        EOF
    - name: Configure metallb L2Advertisement
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: metallb-l2-advertisement
          namespace: metallb-system
        spec:
          ipAddressPools:
          - first-pool
        EOF
    - name: Add Longhorn Repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "{{ longhorn_helm_chart_url }}"
    - name: Install Longhorn
      kubernetes.core.helm:
        name: longhorn
        namespace: longhorn-system
        chart_ref: longhorn/longhorn
        create_namespace: true
    - name: Pause for deployment 
      pause:
        minutes: 1
    - name: Add NGINX Repo
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "{{ nginx_helm_chart_url }}"
    - name: Install Longhorn
      kubernetes.core.helm:
        name: ingress-nginx
        namespace: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        create_namespace: true
    - name: Pause for deployment 
      pause:
        minutes: 1
