apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits"
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "3"
        memory: "6Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
    -
      type: "Container"
      max:
        cpu: "3"
        memory: "6Gi"
      min:
        cpu: "100m"
        memory: "4Mi"
      default:
        cpu: "300m"
        memory: "200Mi"
      defaultRequest:
        cpu: "200m"
        memory: "100Mi"
      maxLimitRequestRatio:
        cpu: "10"