apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.0.0
    helm:
      releaseName: postgres
      valueFiles:
        - values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev