apiVersion: v1
kind: Service
metadata:
  name: postgressql-service
  labels:
    # This should match helm chart labels
    app.kubernetes.io/name: postgresql-ha
spec:
  selector:
    app.kubernetes.io/name: postgresql-ha
  ports:
  - name: expose
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: LoadBalancer