apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: DevOps/Kubernetes/Pipeline/app-in-apps/apps-children/dev
    repoURL: https://github.com/011000100110111101101111/Nexus.git
    targetRevision: HEAD
