apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-longhorn-claim
  namespace: homelab
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi