- hosts: masters
  become: yes # Run as root
  # TODO: Remove redundant commands
  vars:
    user: user
    metallbstart: "192.168.3.230"
    metallbend: "192.168.3.240"
  tasks:
    - name: Install Helm
      command: sudo snap install helm --classic
      become: yes
    - name: Prep Metallb
      shell: |
        kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system
      become: yes
      become_user: "{{ user }}"
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
    - name: Install metallb
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        namespace: metallb-system
      become: yes
      become_user: "{{ user }}"
    - name: Configure metallb IP address pool
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: first-pool
          namespace: metallb-system
        spec:
          addresses:
          - {{ metallbstart }}-{{ metallbend }}
        EOF
      become: yes
      become_user: "{{ user }}"
    - name: Configure metallb L2Advertisement
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: metallb-l2-advertisement
          namespace: metallb-system
        spec:
          ipAddressPools:
          - first-pool
        EOF
      become: yes
      become_user: "{{ user }}"
    - name: Rolling restart of metallb pods
      command: kubectl rollout restart deployment controller -n metallb-system
      become_user: "{{ user }}"
      become: yes
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
    - name: Install Longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        namespace: longhorn-system
      become: yes
      become_user: "{{ user }}"
    - name: Install NGINX Ingress controller
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
      become: yes
      become_user: "{{ user }}"
    - name: Install NGINX Ingress controller
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        namespace: ingress-nginx
      become: yes
      become_user: "{{ user }}"
