title: Nexus
author: Alex Sheehan
description: "Always learning"
baseurl: ""
url: "https://www.nexus-core.dev"
date_format: "%b %-d, %Y"

# Github Build Settings
lsi: false
safe: true
incremental: false
gist:
  noscript: false
permalink: pretty
paginate: 7
paginate_path: "/blog/:num/"
# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"




show_subscribe_cta: false
related_posts: true
compress: false



collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true
  pages:
    output: true
    permalink: /:title/