title: Nexus
author: Alex Sheehan
description: "Always learning"
baseurl: "/Nexus/docs"
url: "https://www.nexus-core.dev"
date_format: "%b %-d, %Y"

# Github Build Settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: pretty
paginate: 7
paginate_path: "/blog/:num/"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"




show_subscribe_cta: false


collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true
  pages:
    output: true
    permalink: /:title/