title: Welcome to Nexus
author: Alex Sheehan
date_format: "%b %-d, %Y"


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-paginate
- jekyll-sitemap


# Optional features
show_related_posts: True
show_post_footers: True
show_subscribe_cta: True
show_social_icons: True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

github_username: 011000100110111101101111
linkedin_username: Alexsheehan01

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

# Build settings
permalink: pretty
paginate: 12
paginate_path: "/blog/:num/"

collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true