- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list_all }}"

- name: Install ubuntu specific packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ specific_package_list_ubuntu }}"

#- name: Loop through manual installations
#  command:
#    cmd: "{{ item }}"
#  loop: "{{ manual_installations }}"