- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list_all }}"

- name: Install ubuntu specific packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ specific_package_list_ubuntu }}"

#- name: Loop through manual installations
#  command:
#    cmd: "{{ item }}"
#  loop: "{{ manual_installations }}"